development:
  adapter: postgresql
  encoding: unicode
  database: rrsite_development
  pool: 5
  host: localhost
  username: postgres
  password:

test: &test
  adapter: postgresql
  encoding: unicode
  database: rrsite_test
  pool: 5
  host: localhost
  username: postgres
  password:

staging:
  adapter: postgresql
  encoding: unicode
  database: rrsite_staging
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: rrsite_production
  pool: 5
  username: postgres
  password:

cucumber:
  <<: *test